package com.ali.jadom.bootstrap;

import java.io.Serializable;

import com.ali.jadom.ApplicationManager;

public enum Bootstrap400Beta implements Serializable, BootEnum{ 
	active
	,alert
	,alert_danger
	,alert_dark
	,alert_dismissible
	,alert_heading
	,alert_info
	,alert_light
	,alert_link
	,alert_primary
	,alert_secondary
	,alert_success
	,alert_warning
	,align_baseline
	,align_bottom
	,align_content_around
	,align_content_between
	,align_content_center
	,align_content_end
	,align_content_lg_around
	,align_content_lg_between
	,align_content_lg_center
	,align_content_lg_end
	,align_content_lg_start
	,align_content_lg_stretch
	,align_content_md_around
	,align_content_md_between
	,align_content_md_center
	,align_content_md_end
	,align_content_md_start
	,align_content_md_stretch
	,align_content_sm_around
	,align_content_sm_between
	,align_content_sm_center
	,align_content_sm_end
	,align_content_sm_start
	,align_content_sm_stretch
	,align_content_start
	,align_content_stretch
	,align_content_xl_around
	,align_content_xl_between
	,align_content_xl_center
	,align_content_xl_end
	,align_content_xl_start
	,align_content_xl_stretch
	,align_items_baseline
	,align_items_center
	,align_items_end
	,align_items_lg_baseline
	,align_items_lg_center
	,align_items_lg_end
	,align_items_lg_start
	,align_items_lg_stretch
	,align_items_md_baseline
	,align_items_md_center
	,align_items_md_end
	,align_items_md_start
	,align_items_md_stretch
	,align_items_sm_baseline
	,align_items_sm_center
	,align_items_sm_end
	,align_items_sm_start
	,align_items_sm_stretch
	,align_items_start
	,align_items_stretch
	,align_items_xl_baseline
	,align_items_xl_center
	,align_items_xl_end
	,align_items_xl_start
	,align_items_xl_stretch
	,align_middle
	,align_self_auto
	,align_self_baseline
	,align_self_center
	,align_self_end
	,align_self_lg_auto
	,align_self_lg_baseline
	,align_self_lg_center
	,align_self_lg_end
	,align_self_lg_start
	,align_self_lg_stretch
	,align_self_md_auto
	,align_self_md_baseline
	,align_self_md_center
	,align_self_md_end
	,align_self_md_start
	,align_self_md_stretch
	,align_self_sm_auto
	,align_self_sm_baseline
	,align_self_sm_center
	,align_self_sm_end
	,align_self_sm_start
	,align_self_sm_stretch
	,align_self_start
	,align_self_stretch
	,align_self_xl_auto
	,align_self_xl_baseline
	,align_self_xl_center
	,align_self_xl_end
	,align_self_xl_start
	,align_self_xl_stretch
	,align_text_bottom
	,align_text_top
	,align_top
	,arrow
	,badge
	,badge_danger
	,badge_dark
	,badge_info
	,badge_light
	,badge_pill
	,badge_primary
	,badge_secondary
	,badge_success
	,badge_warning
	,bg_danger
	,bg_dark
	,bg_info
	,bg_light
	,bg_primary
	,bg_secondary
	,bg_success
	,bg_transparent
	,bg_warning
	,bg_white
	,blockquote
	,blockquote_footer
	,border
	,border_0
	,border_bottom_0
	,border_danger
	,border_dark
	,border_info
	,border_left_0
	,border_light
	,border_primary
	,border_right_0
	,border_secondary
	,border_success
	,border_top_0
	,border_warning
	,border_white
	,breadcrumb
	,breadcrumb_item
	,bs_popover_auto
	,bs_popover_bottom
	,bs_popover_left
	,bs_popover_right
	,bs_popover_top
	,bs_tooltip_auto
	,bs_tooltip_bottom
	,bs_tooltip_left
	,bs_tooltip_right
	,bs_tooltip_top
	,btn
	,btn_block
	,btn_danger
	,btn_dark
	,btn_group
	,btn_group_lg
	,btn_group_sm
	,btn_group_vertical
	,btn_info
	,btn_lg
	,btn_light
	,btn_link
	,btn_outline_danger
	,btn_outline_dark
	,btn_outline_info
	,btn_outline_light
	,btn_outline_primary
	,btn_outline_secondary
	,btn_outline_success
	,btn_outline_warning
	,btn_primary
	,btn_secondary
	,btn_sm
	,btn_success
	,btn_toolbar
	,btn_warning
	,card
	,card_body
	,card_columns
	,card_deck
	,card_footer
	,card_group
	,card_header
	,card_header_pills
	,card_header_tabs
	,card_img
	,card_img_bottom
	,card_img_overlay
	,card_img_top
	,card_link
	,card_subtitle
	,card_text
	,card_title
	,carousel
	,carousel_caption
	,carousel_control_next
	,carousel_control_next_icon
	,carousel_control_prev
	,carousel_control_prev_icon
	,carousel_indicators
	,carousel_inner
	,carousel_item
	,carousel_item_left
	,carousel_item_next
	,carousel_item_prev
	,carousel_item_right
	,clearfix
	,close
	,col
	,col_1
	,col_10
	,col_11
	,col_12
	,col_2
	,col_3
	,col_4
	,col_5
	,col_6
	,col_7
	,col_8
	,col_9
	,col_auto
	,col_form_label
	,col_form_label_lg
	,col_form_label_sm
	,col_form_legend
	,col_lg
	,col_lg_1
	,col_lg_10
	,col_lg_11
	,col_lg_12
	,col_lg_2
	,col_lg_3
	,col_lg_4
	,col_lg_5
	,col_lg_6
	,col_lg_7
	,col_lg_8
	,col_lg_9
	,col_lg_auto
	,col_md
	,col_md_1
	,col_md_10
	,col_md_11
	,col_md_12
	,col_md_2
	,col_md_3
	,col_md_4
	,col_md_5
	,col_md_6
	,col_md_7
	,col_md_8
	,col_md_9
	,col_md_auto
	,col_sm
	,col_sm_1
	,col_sm_10
	,col_sm_11
	,col_sm_12
	,col_sm_2
	,col_sm_3
	,col_sm_4
	,col_sm_5
	,col_sm_6
	,col_sm_7
	,col_sm_8
	,col_sm_9
	,col_sm_auto
	,col_xl
	,col_xl_1
	,col_xl_10
	,col_xl_11
	,col_xl_12
	,col_xl_2
	,col_xl_3
	,col_xl_4
	,col_xl_5
	,col_xl_6
	,col_xl_7
	,col_xl_8
	,col_xl_9
	,col_xl_auto
	,collapse
	,collapsing
	,container
	,container_fluid
	,custom_checkbox
	,custom_control
	,custom_control_description
	,custom_control_indicator
	,custom_control_input
	,custom_controls_stacked
	,custom_file
	,custom_file_control
	,custom_file_input
	,custom_radio
	,custom_select
	,custom_select_sm
	,d_block
	,d_flex
	,d_inline
	,d_inline_block
	,d_inline_flex
	,d_lg_block
	,d_lg_flex
	,d_lg_inline
	,d_lg_inline_block
	,d_lg_inline_flex
	,d_lg_none
	,d_lg_table
	,d_lg_table_cell
	,d_lg_table_row
	,d_md_block
	,d_md_flex
	,d_md_inline
	,d_md_inline_block
	,d_md_inline_flex
	,d_md_none
	,d_md_table
	,d_md_table_cell
	,d_md_table_row
	,d_none
	,d_print_block
	,d_print_inline
	,d_print_inline_block
	,d_print_none
	,d_sm_block
	,d_sm_flex
	,d_sm_inline
	,d_sm_inline_block
	,d_sm_inline_flex
	,d_sm_none
	,d_sm_table
	,d_sm_table_cell
	,d_sm_table_row
	,d_table
	,d_table_cell
	,d_table_row
	,d_xl_block
	,d_xl_flex
	,d_xl_inline
	,d_xl_inline_block
	,d_xl_inline_flex
	,d_xl_none
	,d_xl_table
	,d_xl_table_cell
	,d_xl_table_row
	,disabled
	,display_1
	,display_2
	,display_3
	,display_4
	,dropdown
	,dropdown_divider
	,dropdown_header
	,dropdown_item
	,dropdown_menu
	,dropdown_menu_right
	,dropdown_toggle
	,dropdown_toggle_split
	,dropup
	,embed_responsive
	,embed_responsive_16by9
	,embed_responsive_1by1
	,embed_responsive_21by9
	,embed_responsive_4by3
	,embed_responsive_item
	,fade
	,figure
	,figure_caption
	,figure_img
	,fixed_bottom
	,fixed_top
	,flex_column
	,flex_column_reverse
	,flex_lg_column
	,flex_lg_column_reverse
	,flex_lg_nowrap
	,flex_lg_row
	,flex_lg_row_reverse
	,flex_lg_wrap
	,flex_lg_wrap_reverse
	,flex_md_column
	,flex_md_column_reverse
	,flex_md_nowrap
	,flex_md_row
	,flex_md_row_reverse
	,flex_md_wrap
	,flex_md_wrap_reverse
	,flex_nowrap
	,flex_row
	,flex_row_reverse
	,flex_sm_column
	,flex_sm_column_reverse
	,flex_sm_nowrap
	,flex_sm_row
	,flex_sm_row_reverse
	,flex_sm_wrap
	,flex_sm_wrap_reverse
	,flex_wrap
	,flex_wrap_reverse
	,flex_xl_column
	,flex_xl_column_reverse
	,flex_xl_nowrap
	,flex_xl_row
	,flex_xl_row_reverse
	,flex_xl_wrap
	,flex_xl_wrap_reverse
	,float_left
	,float_lg_left
	,float_lg_none
	,float_lg_right
	,float_md_left
	,float_md_none
	,float_md_right
	,float_none
	,float_right
	,float_sm_left
	,float_sm_none
	,float_sm_right
	,float_xl_left
	,float_xl_none
	,float_xl_right
	,focus
	,font_italic
	,font_weight_bold
	,font_weight_light
	,font_weight_normal
	,form_check
	,form_check_inline
	,form_check_input
	,form_check_label
	,form_control
	,form_control_feedback
	,form_control_file
	,form_control_lg
	,form_control_plaintext
	,form_control_range
	,form_control_sm
	,form_group
	,form_inline
	,form_row
	,form_text
	,h_100
	,h_25
	,h_50
	,h_75
	,h1
	,h2
	,h3
	,h4
	,h5
	,h6
	,has_feedback
	,img_fluid
	,img_thumbnail
	,initialism
	,input_group
	,input_group_addon
	,input_group_btn
	,input_group_lg
	,input_group_sm
	,invalid_feedback
	,invalid_tooltip
	,invisible
	,is_invalid
	,is_valid
	,jumbotron
	,jumbotron_fluid
	,justify_content_around
	,justify_content_between
	,justify_content_center
	,justify_content_end
	,justify_content_lg_around
	,justify_content_lg_between
	,justify_content_lg_center
	,justify_content_lg_end
	,justify_content_lg_start
	,justify_content_md_around
	,justify_content_md_between
	,justify_content_md_center
	,justify_content_md_end
	,justify_content_md_start
	,justify_content_sm_around
	,justify_content_sm_between
	,justify_content_sm_center
	,justify_content_sm_end
	,justify_content_sm_start
	,justify_content_start
	,justify_content_xl_around
	,justify_content_xl_between
	,justify_content_xl_center
	,justify_content_xl_end
	,justify_content_xl_start
	,lead
	,list_group
	,list_group_flush
	,list_group_item
	,list_group_item_action
	,list_group_item_danger
	,list_group_item_dark
	,list_group_item_info
	,list_group_item_light
	,list_group_item_primary
	,list_group_item_secondary
	,list_group_item_success
	,list_group_item_warning
	,list_inline
	,list_inline_item
	,list_unstyled
	,m_0
	,m_1
	,m_2
	,m_3
	,m_4
	,m_5
	,m_auto
	,m_lg_0
	,m_lg_1
	,m_lg_2
	,m_lg_3
	,m_lg_4
	,m_lg_5
	,m_lg_auto
	,m_md_0
	,m_md_1
	,m_md_2
	,m_md_3
	,m_md_4
	,m_md_5
	,m_md_auto
	,m_sm_0
	,m_sm_1
	,m_sm_2
	,m_sm_3
	,m_sm_4
	,m_sm_5
	,m_sm_auto
	,m_xl_0
	,m_xl_1
	,m_xl_2
	,m_xl_3
	,m_xl_4
	,m_xl_5
	,m_xl_auto
	,mark
	,mb_0
	,mb_1
	,mb_2
	,mb_3
	,mb_4
	,mb_5
	,mb_auto
	,mb_lg_0
	,mb_lg_1
	,mb_lg_2
	,mb_lg_3
	,mb_lg_4
	,mb_lg_5
	,mb_lg_auto
	,mb_md_0
	,mb_md_1
	,mb_md_2
	,mb_md_3
	,mb_md_4
	,mb_md_5
	,mb_md_auto
	,mb_sm_0
	,mb_sm_1
	,mb_sm_2
	,mb_sm_3
	,mb_sm_4
	,mb_sm_5
	,mb_sm_auto
	,mb_xl_0
	,mb_xl_1
	,mb_xl_2
	,mb_xl_3
	,mb_xl_4
	,mb_xl_5
	,mb_xl_auto
	,media
	,media_body
	,mh_100
	,ml_0
	,ml_1
	,ml_2
	,ml_3
	,ml_4
	,ml_5
	,ml_auto
	,ml_lg_0
	,ml_lg_1
	,ml_lg_2
	,ml_lg_3
	,ml_lg_4
	,ml_lg_5
	,ml_lg_auto
	,ml_md_0
	,ml_md_1
	,ml_md_2
	,ml_md_3
	,ml_md_4
	,ml_md_5
	,ml_md_auto
	,ml_sm_0
	,ml_sm_1
	,ml_sm_2
	,ml_sm_3
	,ml_sm_4
	,ml_sm_5
	,ml_sm_auto
	,ml_xl_0
	,ml_xl_1
	,ml_xl_2
	,ml_xl_3
	,ml_xl_4
	,ml_xl_5
	,ml_xl_auto
	,modal
	,modal_backdrop
	,modal_body
	,modal_content
	,modal_dialog
	,modal_footer
	,modal_header
	,modal_lg
	,modal_open
	,modal_scrollbar_measure
	,modal_sm
	,modal_title
	,mr_0
	,mr_1
	,mr_2
	,mr_3
	,mr_4
	,mr_5
	,mr_auto
	,mr_lg_0
	,mr_lg_1
	,mr_lg_2
	,mr_lg_3
	,mr_lg_4
	,mr_lg_5
	,mr_lg_auto
	,mr_md_0
	,mr_md_1
	,mr_md_2
	,mr_md_3
	,mr_md_4
	,mr_md_5
	,mr_md_auto
	,mr_sm_0
	,mr_sm_1
	,mr_sm_2
	,mr_sm_3
	,mr_sm_4
	,mr_sm_5
	,mr_sm_auto
	,mr_xl_0
	,mr_xl_1
	,mr_xl_2
	,mr_xl_3
	,mr_xl_4
	,mr_xl_5
	,mr_xl_auto
	,mt_0
	,mt_1
	,mt_2
	,mt_3
	,mt_4
	,mt_5
	,mt_auto
	,mt_lg_0
	,mt_lg_1
	,mt_lg_2
	,mt_lg_3
	,mt_lg_4
	,mt_lg_5
	,mt_lg_auto
	,mt_md_0
	,mt_md_1
	,mt_md_2
	,mt_md_3
	,mt_md_4
	,mt_md_5
	,mt_md_auto
	,mt_sm_0
	,mt_sm_1
	,mt_sm_2
	,mt_sm_3
	,mt_sm_4
	,mt_sm_5
	,mt_sm_auto
	,mt_xl_0
	,mt_xl_1
	,mt_xl_2
	,mt_xl_3
	,mt_xl_4
	,mt_xl_5
	,mt_xl_auto
	,mw_100
	,mx_0
	,mx_1
	,mx_2
	,mx_3
	,mx_4
	,mx_5
	,mx_auto
	,mx_lg_0
	,mx_lg_1
	,mx_lg_2
	,mx_lg_3
	,mx_lg_4
	,mx_lg_5
	,mx_lg_auto
	,mx_md_0
	,mx_md_1
	,mx_md_2
	,mx_md_3
	,mx_md_4
	,mx_md_5
	,mx_md_auto
	,mx_sm_0
	,mx_sm_1
	,mx_sm_2
	,mx_sm_3
	,mx_sm_4
	,mx_sm_5
	,mx_sm_auto
	,mx_xl_0
	,mx_xl_1
	,mx_xl_2
	,mx_xl_3
	,mx_xl_4
	,mx_xl_5
	,mx_xl_auto
	,my_0
	,my_1
	,my_2
	,my_3
	,my_4
	,my_5
	,my_auto
	,my_lg_0
	,my_lg_1
	,my_lg_2
	,my_lg_3
	,my_lg_4
	,my_lg_5
	,my_lg_auto
	,my_md_0
	,my_md_1
	,my_md_2
	,my_md_3
	,my_md_4
	,my_md_5
	,my_md_auto
	,my_sm_0
	,my_sm_1
	,my_sm_2
	,my_sm_3
	,my_sm_4
	,my_sm_5
	,my_sm_auto
	,my_xl_0
	,my_xl_1
	,my_xl_2
	,my_xl_3
	,my_xl_4
	,my_xl_5
	,my_xl_auto
	,nav
	,nav_fill
	,nav_item
	,nav_justified
	,nav_link
	,nav_pills
	,nav_tabs
	,navbar
	,navbar_brand
	,navbar_collapse
	,navbar_dark
	,navbar_expand
	,navbar_expand_lg
	,navbar_expand_md
	,navbar_expand_sm
	,navbar_expand_xl
	,navbar_light
	,navbar_nav
	,navbar_text
	,navbar_toggler
	,navbar_toggler_icon
	,no_gutters
	,offset_1
	,offset_10
	,offset_11
	,offset_2
	,offset_3
	,offset_4
	,offset_5
	,offset_6
	,offset_7
	,offset_8
	,offset_9
	,offset_lg_0
	,offset_lg_1
	,offset_lg_10
	,offset_lg_11
	,offset_lg_2
	,offset_lg_3
	,offset_lg_4
	,offset_lg_5
	,offset_lg_6
	,offset_lg_7
	,offset_lg_8
	,offset_lg_9
	,offset_md_0
	,offset_md_1
	,offset_md_10
	,offset_md_11
	,offset_md_2
	,offset_md_3
	,offset_md_4
	,offset_md_5
	,offset_md_6
	,offset_md_7
	,offset_md_8
	,offset_md_9
	,offset_sm_0
	,offset_sm_1
	,offset_sm_10
	,offset_sm_11
	,offset_sm_2
	,offset_sm_3
	,offset_sm_4
	,offset_sm_5
	,offset_sm_6
	,offset_sm_7
	,offset_sm_8
	,offset_sm_9
	,offset_xl_0
	,offset_xl_1
	,offset_xl_10
	,offset_xl_11
	,offset_xl_2
	,offset_xl_3
	,offset_xl_4
	,offset_xl_5
	,offset_xl_6
	,offset_xl_7
	,offset_xl_8
	,offset_xl_9
	,order_1
	,order_10
	,order_11
	,order_12
	,order_2
	,order_3
	,order_4
	,order_5
	,order_6
	,order_7
	,order_8
	,order_9
	,order_first
	,order_lg_1
	,order_lg_10
	,order_lg_11
	,order_lg_12
	,order_lg_2
	,order_lg_3
	,order_lg_4
	,order_lg_5
	,order_lg_6
	,order_lg_7
	,order_lg_8
	,order_lg_9
	,order_lg_first
	,order_md_1
	,order_md_10
	,order_md_11
	,order_md_12
	,order_md_2
	,order_md_3
	,order_md_4
	,order_md_5
	,order_md_6
	,order_md_7
	,order_md_8
	,order_md_9
	,order_md_first
	,order_sm_1
	,order_sm_10
	,order_sm_11
	,order_sm_12
	,order_sm_2
	,order_sm_3
	,order_sm_4
	,order_sm_5
	,order_sm_6
	,order_sm_7
	,order_sm_8
	,order_sm_9
	,order_sm_first
	,order_xl_1
	,order_xl_10
	,order_xl_11
	,order_xl_12
	,order_xl_2
	,order_xl_3
	,order_xl_4
	,order_xl_5
	,order_xl_6
	,order_xl_7
	,order_xl_8
	,order_xl_9
	,order_xl_first
	,p_0
	,p_1
	,p_2
	,p_3
	,p_4
	,p_5
	,p_lg_0
	,p_lg_1
	,p_lg_2
	,p_lg_3
	,p_lg_4
	,p_lg_5
	,p_md_0
	,p_md_1
	,p_md_2
	,p_md_3
	,p_md_4
	,p_md_5
	,p_sm_0
	,p_sm_1
	,p_sm_2
	,p_sm_3
	,p_sm_4
	,p_sm_5
	,p_xl_0
	,p_xl_1
	,p_xl_2
	,p_xl_3
	,p_xl_4
	,p_xl_5
	,page_item
	,page_link
	,pagination
	,pagination_lg
	,pagination_sm
	,pb_0
	,pb_1
	,pb_2
	,pb_3
	,pb_4
	,pb_5
	,pb_lg_0
	,pb_lg_1
	,pb_lg_2
	,pb_lg_3
	,pb_lg_4
	,pb_lg_5
	,pb_md_0
	,pb_md_1
	,pb_md_2
	,pb_md_3
	,pb_md_4
	,pb_md_5
	,pb_sm_0
	,pb_sm_1
	,pb_sm_2
	,pb_sm_3
	,pb_sm_4
	,pb_sm_5
	,pb_xl_0
	,pb_xl_1
	,pb_xl_2
	,pb_xl_3
	,pb_xl_4
	,pb_xl_5
	,pl_0
	,pl_1
	,pl_2
	,pl_3
	,pl_4
	,pl_5
	,pl_lg_0
	,pl_lg_1
	,pl_lg_2
	,pl_lg_3
	,pl_lg_4
	,pl_lg_5
	,pl_md_0
	,pl_md_1
	,pl_md_2
	,pl_md_3
	,pl_md_4
	,pl_md_5
	,pl_sm_0
	,pl_sm_1
	,pl_sm_2
	,pl_sm_3
	,pl_sm_4
	,pl_sm_5
	,pl_xl_0
	,pl_xl_1
	,pl_xl_2
	,pl_xl_3
	,pl_xl_4
	,pl_xl_5
	,popover
	,popover_body
	,popover_header
	,position_absolute
	,position_fixed
	,position_relative
	,position_static
	,position_sticky
	,pr_0
	,pr_1
	,pr_2
	,pr_3
	,pr_4
	,pr_5
	,pr_lg_0
	,pr_lg_1
	,pr_lg_2
	,pr_lg_3
	,pr_lg_4
	,pr_lg_5
	,pr_md_0
	,pr_md_1
	,pr_md_2
	,pr_md_3
	,pr_md_4
	,pr_md_5
	,pr_sm_0
	,pr_sm_1
	,pr_sm_2
	,pr_sm_3
	,pr_sm_4
	,pr_sm_5
	,pr_xl_0
	,pr_xl_1
	,pr_xl_2
	,pr_xl_3
	,pr_xl_4
	,pr_xl_5
	,pre_scrollable
	,progress
	,progress_bar
	,progress_bar_animated
	,progress_bar_striped
	,pt_0
	,pt_1
	,pt_2
	,pt_3
	,pt_4
	,pt_5
	,pt_lg_0
	,pt_lg_1
	,pt_lg_2
	,pt_lg_3
	,pt_lg_4
	,pt_lg_5
	,pt_md_0
	,pt_md_1
	,pt_md_2
	,pt_md_3
	,pt_md_4
	,pt_md_5
	,pt_sm_0
	,pt_sm_1
	,pt_sm_2
	,pt_sm_3
	,pt_sm_4
	,pt_sm_5
	,pt_xl_0
	,pt_xl_1
	,pt_xl_2
	,pt_xl_3
	,pt_xl_4
	,pt_xl_5
	,px_0
	,px_1
	,px_2
	,px_3
	,px_4
	,px_5
	,px_lg_0
	,px_lg_1
	,px_lg_2
	,px_lg_3
	,px_lg_4
	,px_lg_5
	,px_md_0
	,px_md_1
	,px_md_2
	,px_md_3
	,px_md_4
	,px_md_5
	,px_sm_0
	,px_sm_1
	,px_sm_2
	,px_sm_3
	,px_sm_4
	,px_sm_5
	,px_xl_0
	,px_xl_1
	,px_xl_2
	,px_xl_3
	,px_xl_4
	,px_xl_5
	,py_0
	,py_1
	,py_2
	,py_3
	,py_4
	,py_5
	,py_lg_0
	,py_lg_1
	,py_lg_2
	,py_lg_3
	,py_lg_4
	,py_lg_5
	,py_md_0
	,py_md_1
	,py_md_2
	,py_md_3
	,py_md_4
	,py_md_5
	,py_sm_0
	,py_sm_1
	,py_sm_2
	,py_sm_3
	,py_sm_4
	,py_sm_5
	,py_xl_0
	,py_xl_1
	,py_xl_2
	,py_xl_3
	,py_xl_4
	,py_xl_5
	,rounded
	,rounded_0
	,rounded_bottom
	,rounded_circle
	,rounded_left
	,rounded_right
	,rounded_top
	,row
	,show
	,slide
	,small
	,sr_only
	,sr_only_focusable
	,tab_content
	,tab_pane
	,table
	,table_active
	,table_bordered
	,table_danger
	,table_dark
	,table_hover
	,table_info
	,table_light
	,table_primary
	,table_responsive
	,table_responsive_lg
	,table_responsive_md
	,table_responsive_sm
	,table_responsive_xl
	,table_secondary
	,table_sm
	,table_striped
	,table_success
	,table_warning
	,text_capitalize
	,text_center
	,text_danger
	,text_dark
	,text_hide
	,text_info
	,text_justify
	,text_left
	,text_lg_center
	,text_lg_left
	,text_lg_right
	,text_light
	,text_lowercase
	,text_md_center
	,text_md_left
	,text_md_right
	,text_muted
	,text_nowrap
	,text_primary
	,text_right
	,text_secondary
	,text_sm_center
	,text_sm_left
	,text_sm_right
	,text_success
	,text_truncate
	,text_uppercase
	,text_warning
	,text_white
	,text_xl_center
	,text_xl_left
	,text_xl_right
	,thead_dark
	,thead_light
	,tooltip
	,tooltip_inner
	,valid_feedback
	,valid_tooltip
	,visible
	,w_100
	,w_25
	,w_50
	,w_75
	,was_validated;

	@Override
	public String toString() {
		return ApplicationManager.STRING_SPACE.concat(this.name().replaceAll("_", "-"));
	}
	
	public DOMclass toDomClass() {
		return new DOMclass(this.toString());
	}
} 
